### ISSUE TITLE
关于tusimple数据集class的处理

### ISSUE THREAD

**Issue by qklee-lz** [ZJULearning/resa#27]
您好：
请问tusimple数据集，再tool里做了些处理，其中计算每条车道线的正切值，然后利用正切值对车道线进行了class分类，请问这个是图森数据集要求这么做的还是其他原因呢？我看数据集的介绍里也没有去定义每条车道线的class, 这个地方我很疑惑；同样，网络推理出的车道线的seg和gt算了socre, 而exist虽然设置了>0.5的阈值就置1，但实际去算分和一些后处理的时候并没有起作用，所以我很好奇这个class即其对应的exist的作用是什么～^_^

**Comment by Turoad** [comment]
We regrad the lane detection as an instance segmentation problem, which helps us easily get different lane instances. If we only segment lane mask (1 for lane pixel, 0 for background), we need to postprocess to get the different lanes, like LaneNet.  We can get better performance with lane instance result without postprocess.

As for the exist head, we just keep the network same as CULane. In fact, we don't use the exist result because it may bring performance drop.

**Comment by qklee-lz** [comment]
> We regrad the lane detection as an instance segmentation problem, which helps us easily get different lane instances. If we only segment lane mask (1 for lane pixel, 0 for background), we need to postprocess to get the different lanes, like LaneNet. We can get better performance with lane instance result without postprocess.
> 
> As for the exist head, we just keep the network same as CULane. In fact, we don't use the exist result because it may bring performance drop.

**Comment by qklee-lz** [comment]
Thank you very much for your reply！And Your reply is very clear, I understand~😄
